local M = {}

--- Highlights grouped per plugin. Any key can be turned off with
--- `plugins = { <key> = false }`.
---@param c table<string, string>
---@param o Dark2026Config
---@return table<string, table<string, table>>
function M.get(c, o)
  return {
    gitsigns = {
      GitSignsAdd = { fg = c.diff_add_fg },
      GitSignsChange = { fg = c.warn },
      GitSignsDelete = { fg = c.diff_del_fg },
      GitSignsAddInline = { bg = c.diff_add },
      GitSignsChangeInline = { bg = c.diff_chg },
      GitSignsDeleteInline = { bg = c.diff_del },
      GitSignsCurrentLineBlame = { fg = c.fg_muted, italic = true },
    },

    telescope = {
      TelescopeNormal = { fg = c.fg, bg = c.bg_float },
      TelescopeBorder = { fg = c.border, bg = c.bg_float },
      TelescopeTitle = { fg = c.fg_alt, bold = true },
      TelescopePromptNormal = { fg = c.fg, bg = c.bg_float },
      TelescopePromptBorder = { fg = c.border_alt, bg = c.bg_float },
      TelescopePromptTitle = { fg = c.accent_alt, bold = true },
      TelescopePromptPrefix = { fg = c.accent },
      TelescopeResultsTitle = { fg = c.fg_dim },
      TelescopePreviewTitle = { fg = c.fg_dim },
      TelescopeSelection = { fg = c.fg_alt, bg = c.accent_dim },
      TelescopeSelectionCaret = { fg = c.accent, bg = c.accent_dim },
      TelescopeMultiSelection = { fg = c.func },
      TelescopeMatching = { fg = c.accent_alt, bold = true },
    },

    fzf_lua = {
      FzfLuaNormal = { fg = c.fg, bg = c.bg_float },
      FzfLuaBorder = { fg = c.border, bg = c.bg_float },
      FzfLuaTitle = { fg = c.accent_alt, bold = true },
      FzfLuaCursorLine = { fg = c.fg_alt, bg = c.accent_dim },
      FzfLuaFzfMatch = { fg = c.accent_alt, bold = true },
      FzfLuaHeaderText = { fg = c.keyword },
      FzfLuaHeaderBind = { fg = c.func },
      FzfLuaPathLineNr = { fg = c.fg_dim },
      FzfLuaBufNr = { fg = c.fg_dim },
    },

    snacks = {
      SnacksPickerNormal = { fg = c.fg, bg = c.bg_float },
      SnacksPickerBorder = { fg = c.border, bg = c.bg_float },
      SnacksPickerTitle = { fg = c.accent_alt, bold = true },
      SnacksPickerInputBorder = { fg = c.accent_dim, bg = c.bg_float },
      SnacksPickerInputSearch = { fg = c.accent },
      SnacksPickerListCursorLine = { bg = c.bg_line },
      SnacksPickerMatch = { fg = c.accent_alt, bold = true },
      SnacksPickerDir = { fg = c.comment },
      SnacksPickerFile = { fg = c.fg },
      SnacksPickerIdx = { fg = c.fg_muted },
      SnacksNotifierInfo = { fg = c.info, bg = c.bg_float },
      SnacksNotifierWarn = { fg = c.warn, bg = c.bg_float },
      SnacksNotifierError = { fg = c.err, bg = c.bg_float },
      SnacksNotifierDebug = { fg = c.debug, bg = c.bg_float },
      SnacksNotifierTrace = { fg = c.fg_dim, bg = c.bg_float },
      SnacksDashboardHeader = { fg = c.accent },
      SnacksDashboardIcon = { fg = c.func },
      SnacksDashboardDesc = { fg = c.fg },
      SnacksDashboardKey = { fg = c.annotation },
      SnacksDashboardTitle = { fg = c.accent_alt, bold = true },
      SnacksDashboardFooter = { fg = c.fg_dim, italic = true },
      SnacksIndent = { fg = c.border },
      SnacksIndentScope = { fg = c.accent_dim },
    },

    blink = {
      BlinkCmpMenu = { link = 'Pmenu' },
      BlinkCmpMenuBorder = { fg = c.border_alt, bg = c.bg_float },
      BlinkCmpMenuSelection = { link = 'PmenuSel' },
      BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
      BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
      BlinkCmpLabel = { fg = c.fg },
      BlinkCmpLabelMatch = { fg = c.accent_alt, bold = true },
      BlinkCmpLabelDeprecated = { fg = c.fg_muted, strikethrough = true },
      BlinkCmpLabelDetail = { fg = c.fg_dim },
      BlinkCmpLabelDescription = { fg = c.fg_dim },
      BlinkCmpKind = { fg = c.func },
      BlinkCmpSource = { fg = c.fg_dim },
      BlinkCmpDoc = { link = 'NormalFloat' },
      BlinkCmpDocBorder = { fg = c.border_alt, bg = c.bg_float },
      BlinkCmpDocSeparator = { fg = c.border },
      BlinkCmpSignatureHelp = { link = 'NormalFloat' },
      BlinkCmpSignatureHelpBorder = { fg = c.border_alt, bg = c.bg_float },
      BlinkCmpSignatureHelpActiveParameter = { fg = c.param, bold = true },
      BlinkCmpGhostText = { fg = c.fg_muted },
    },

    cmp = {
      CmpItemAbbr = { fg = c.fg },
      CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
      CmpItemAbbrMatch = { fg = c.accent_alt, bold = true },
      CmpItemAbbrMatchFuzzy = { fg = c.accent_alt, bold = true },
      CmpItemMenu = { fg = c.fg_dim },
      CmpItemKind = { fg = c.func },
      CmpItemKindText = { fg = c.fg },
      CmpItemKindVariable = { fg = c.variable },
      CmpItemKindFunction = { fg = c.func },
      CmpItemKindMethod = { fg = c.func },
      CmpItemKindConstructor = { fg = c.type },
      CmpItemKindClass = { fg = c.type },
      CmpItemKindStruct = { fg = c.type },
      CmpItemKindInterface = { fg = c.type },
      CmpItemKindModule = { fg = c.module },
      CmpItemKindProperty = { fg = c.member },
      CmpItemKindField = { fg = c.member },
      CmpItemKindEnum = { fg = c.type },
      CmpItemKindEnumMember = { fg = c.constant },
      CmpItemKindKeyword = { fg = c.keyword },
      CmpItemKindSnippet = { fg = c.regex },
      CmpItemKindConstant = { fg = c.constant },
      CmpItemKindFile = { fg = c.fg },
      CmpItemKindFolder = { fg = c.accent_alt },
      CmpGhostText = { fg = c.fg_muted },
    },

    bufferline = {
      BufferLineFill = { bg = c.bg_panel },
      BufferLineBackground = { fg = c.fg_dim, bg = c.bg_panel },
      BufferLineBufferSelected = { fg = c.fg_alt, bg = c.bg_normal, bold = true },
      BufferLineBufferVisible = { fg = c.fg_dim, bg = c.bg_panel },
      BufferLineIndicatorSelected = { fg = c.accent, bg = c.bg_normal },
      BufferLineSeparator = { fg = c.border, bg = c.bg_panel },
      BufferLineSeparatorSelected = { fg = c.border, bg = c.bg_normal },
      BufferLineModified = { fg = c.warn, bg = c.bg_panel },
      BufferLineModifiedSelected = { fg = c.warn, bg = c.bg_normal },
      BufferLineCloseButton = { fg = c.fg_dim, bg = c.bg_panel },
      BufferLineCloseButtonSelected = { fg = c.keyword, bg = c.bg_normal },
    },

    which_key = {
      WhichKey = { fg = c.keyword },
      WhichKeyGroup = { fg = c.func },
      WhichKeyDesc = { fg = c.fg },
      WhichKeySeparator = { fg = c.fg_dim },
      WhichKeyValue = { fg = c.fg_dim },
      WhichKeyBorder = { fg = c.border_alt, bg = c.bg_float },
      WhichKeyNormal = { bg = c.bg_float },
      WhichKeyFloat = { bg = c.bg_float },
      WhichKeyTitle = { fg = c.accent_alt, bold = true },
    },

    notify = {
      NotifyERRORBorder = { fg = c.err },
      NotifyWARNBorder = { fg = c.warn },
      NotifyINFOBorder = { fg = c.info },
      NotifyDEBUGBorder = { fg = c.debug },
      NotifyTRACEBorder = { fg = c.fg_dim },
      NotifyERRORIcon = { fg = c.err },
      NotifyWARNIcon = { fg = c.warn },
      NotifyINFOIcon = { fg = c.info },
      NotifyDEBUGIcon = { fg = c.debug },
      NotifyTRACEIcon = { fg = c.fg_dim },
      NotifyERRORTitle = { fg = c.err, bold = true },
      NotifyWARNTitle = { fg = c.warn, bold = true },
      NotifyINFOTitle = { fg = c.info, bold = true },
      NotifyDEBUGTitle = { fg = c.debug, bold = true },
      NotifyTRACETitle = { fg = c.fg_dim, bold = true },
      NotifyBackground = { fg = c.fg, bg = c.bg_float },
    },

    noice = {
      NoiceCmdline = { fg = c.fg, bg = c.bg_float },
      NoiceCmdlineIcon = { fg = c.accent },
      NoiceCmdlineIconSearch = { fg = c.warn },
      NoiceCmdlinePopup = { fg = c.fg, bg = c.bg_float },
      NoiceCmdlinePopupBorder = { fg = c.border_alt, bg = c.bg_float },
      NoiceCmdlinePopupTitle = { fg = c.accent_alt, bold = true },
      NoiceConfirmBorder = { fg = c.border_alt, bg = c.bg_float },
      NoicePopupBorder = { fg = c.border_alt, bg = c.bg_float },
      NoiceMini = { fg = c.fg, bg = c.bg_line },
      NoiceVirtualText = { fg = c.fg_dim },
      NoiceLspProgressTitle = { fg = c.fg_alt },
      NoiceLspProgressClient = { fg = c.func },
      NoiceLspProgressSpinner = { fg = c.accent },
    },

    neo_tree = {
      NeoTreeNormal = { fg = c.fg, bg = c.bg_normal },
      NeoTreeNormalNC = { fg = c.fg, bg = c.bg_normal },
      NeoTreeFloatNormal = { fg = c.fg, bg = c.bg_float },
      NeoTreeFloatBorder = { fg = c.border_alt, bg = c.bg_float },
      NeoTreeTitleBar = { fg = c.fg_alt, bg = c.accent_dim },
      NeoTreeWinSeparator = { fg = c.border, bg = c.bg_normal },
      NeoTreeEndOfBuffer = { fg = c.bg },
      NeoTreeRootName = { fg = c.fg_alt, bold = true },
      NeoTreeDirectoryName = { fg = c.fg },
      NeoTreeDirectoryIcon = { fg = c.accent_alt },
      NeoTreeFileName = { fg = c.fg },
      NeoTreeFileIcon = { fg = c.fg_dim },
      NeoTreeIndentMarker = { fg = c.border_alt },
      NeoTreeExpander = { fg = c.fg_muted },
      NeoTreeDotfile = { fg = c.fg_muted },
      NeoTreeGitAdded = { fg = c.diff_add_fg },
      NeoTreeGitModified = { fg = c.warn },
      NeoTreeGitDeleted = { fg = c.diff_del_fg },
      NeoTreeGitIgnored = { fg = c.fg_muted },
      NeoTreeGitUntracked = { fg = c.fg_dim },
      NeoTreeGitConflict = { fg = c.keyword },
      NeoTreeCursorLine = { bg = c.bg_line },
    },

    nvim_tree = {
      NvimTreeNormal = { fg = c.fg, bg = c.bg_normal },
      NvimTreeNormalNC = { fg = c.fg, bg = c.bg_normal },
      NvimTreeWinSeparator = { fg = c.border, bg = c.bg_normal },
      NvimTreeEndOfBuffer = { fg = c.bg },
      NvimTreeRootFolder = { fg = c.fg_alt, bold = true },
      NvimTreeFolderName = { fg = c.fg },
      NvimTreeFolderIcon = { fg = c.accent_alt },
      NvimTreeOpenedFolderName = { fg = c.fg_alt, bold = true },
      NvimTreeSpecialFile = { fg = c.annotation },
      NvimTreeIndentMarker = { fg = c.border_alt },
      NvimTreeGitDirty = { fg = c.warn },
      NvimTreeGitNew = { fg = c.diff_add_fg },
      NvimTreeGitDeleted = { fg = c.diff_del_fg },
      NvimTreeCursorLine = { bg = c.bg_line },
    },

    oil = {
      OilDir = { fg = c.accent_alt },
      OilDirIcon = { fg = c.accent_alt },
      OilFile = { fg = c.fg },
      OilLink = { fg = c.string },
      OilLinkTarget = { fg = c.fg_dim },
      OilCreate = { fg = c.diff_add_fg },
      OilDelete = { fg = c.diff_del_fg },
      OilMove = { fg = c.warn },
      OilCopy = { fg = c.info },
    },

    indent_blankline = {
      IblIndent = { fg = c.border },
      IblWhitespace = { fg = c.border },
      IblScope = { fg = c.accent_dim },
      IndentBlanklineChar = { fg = c.border },
      IndentBlanklineContextChar = { fg = c.accent_dim },
    },

    mini = {
      MiniIndentscopeSymbol = { fg = c.accent_dim },
      MiniIndentscopePrefix = { nocombine = true },
      MiniStatuslineDevinfo = { fg = c.fg_dim, bg = c.bg_panel },
      MiniStatuslineFileinfo = { fg = c.fg_dim, bg = c.bg_panel },
      MiniStatuslineFilename = { fg = c.fg, bg = c.bg_panel },
      MiniStatuslineInactive = { fg = c.fg_muted, bg = c.bg_panel },
      MiniStatuslineModeNormal = { fg = c.bg, bg = c.accent, bold = true },
      MiniStatuslineModeInsert = { fg = c.bg, bg = c.regex, bold = true },
      MiniStatuslineModeVisual = { fg = c.bg, bg = c.func, bold = true },
      MiniStatuslineModeReplace = { fg = c.bg, bg = c.keyword, bold = true },
      MiniStatuslineModeCommand = { fg = c.bg, bg = c.annotation, bold = true },
      MiniStatuslineModeOther = { fg = c.bg, bg = c.type, bold = true },
      MiniTablineCurrent = { fg = c.fg_alt, bg = c.bg_normal, bold = true },
      MiniTablineVisible = { fg = c.fg_dim, bg = c.bg_panel },
      MiniTablineHidden = { fg = c.fg_muted, bg = c.bg_panel },
      MiniTablineFill = { bg = c.bg_panel },
      MiniTablineModifiedCurrent = { fg = c.warn, bg = c.bg_normal },
      MiniTablineModifiedVisible = { fg = c.warn, bg = c.bg_panel },
      MiniTablineModifiedHidden = { fg = c.warn, bg = c.bg_panel },
      MiniPickBorder = { fg = c.border_alt, bg = c.bg_float },
      MiniPickNormal = { fg = c.fg, bg = c.bg_float },
      MiniPickMatchCurrent = { fg = c.fg_alt, bg = c.accent_dim },
      MiniPickMatchRanges = { fg = c.accent_alt, bold = true },
      MiniPickPrompt = { fg = c.accent, bg = c.bg_float },
      MiniFilesTitleFocused = { fg = c.accent_alt, bold = true },
      MiniDiffSignAdd = { fg = c.diff_add_fg },
      MiniDiffSignChange = { fg = c.warn },
      MiniDiffSignDelete = { fg = c.diff_del_fg },
    },

    lazy = {
      LazyNormal = { fg = c.fg, bg = c.bg_float },
      LazyButton = { fg = c.fg, bg = c.bg_line },
      LazyButtonActive = { fg = c.fg_alt, bg = c.accent_dim, bold = true },
      LazyH1 = { fg = c.fg_alt, bg = c.accent_dim, bold = true },
      LazyH2 = { fg = c.keyword, bold = true },
      LazyProgressDone = { fg = c.ok, bold = true },
      LazyProgressTodo = { fg = c.fg_muted },
      LazyCommit = { fg = c.regex },
      LazyReasonPlugin = { fg = c.func },
      LazySpecial = { fg = c.accent_alt },
    },

    mason = {
      MasonNormal = { fg = c.fg, bg = c.bg_float },
      MasonHeader = { fg = c.bg, bg = c.accent, bold = true },
      MasonHeaderSecondary = { fg = c.bg, bg = c.func, bold = true },
      MasonHighlight = { fg = c.accent_alt },
      MasonHighlightBlock = { fg = c.bg, bg = c.type },
      MasonHighlightBlockBold = { fg = c.bg, bg = c.type, bold = true },
      MasonMuted = { fg = c.fg_muted },
      MasonMutedBlock = { fg = c.fg_dim, bg = c.bg_line },
    },

    trouble = {
      TroubleNormal = { fg = c.fg, bg = c.bg_normal },
      TroubleNormalNC = { fg = c.fg, bg = c.bg_normal },
      TroubleText = { fg = c.fg },
      TroubleCount = { fg = c.func, bg = c.bg_line },
      TroubleFile = { fg = c.accent_alt },
      TroubleSource = { fg = c.fg_dim },
      TroubleIndent = { fg = c.border_alt },
      TroublePos = { fg = c.fg_dim },
    },

    flash = {
      FlashBackdrop = { fg = c.fg_muted },
      FlashLabel = { fg = c.white, bg = c.keyword, bold = true },
      FlashMatch = { fg = c.fg, bg = c.bg_match },
      FlashCurrent = { fg = c.white, bg = c.accent },
      FlashPrompt = { fg = c.fg, bg = c.bg_panel },
      FlashPromptIcon = { fg = c.accent },
    },

    illuminate = {
      IlluminatedWordText = { bg = c.bg_widget },
      IlluminatedWordRead = { bg = c.bg_widget },
      IlluminatedWordWrite = { bg = c.bg_widget, underline = true },
    },

    treesitter_context = {
      TreesitterContext = { bg = c.bg_alt },
      TreesitterContextLineNumber = { fg = c.fg_muted, bg = c.bg_alt },
      TreesitterContextBottom = { sp = c.border, underline = true },
      TreesitterContextSeparator = { fg = c.border },
    },

    rainbow = {
      RainbowDelimiterRed = { fg = c.keyword },
      RainbowDelimiterYellow = { fg = c.annotation },
      RainbowDelimiterBlue = { fg = c.number },
      RainbowDelimiterOrange = { fg = c.warn },
      RainbowDelimiterGreen = { fg = c.regex },
      RainbowDelimiterViolet = { fg = c.func },
      RainbowDelimiterCyan = { fg = c.type },
    },

    dap = {
      DapBreakpoint = { fg = c.err },
      DapBreakpointCondition = { fg = c.warn },
      DapLogPoint = { fg = c.info },
      DapStopped = { fg = c.annotation },
      DapStoppedLine = { bg = c.bg_line },
      DapUIVariable = { fg = c.variable },
      DapUIScope = { fg = c.accent_alt },
      DapUIType = { fg = c.type },
      DapUIValue = { fg = c.fg },
      DapUIModifiedValue = { fg = c.accent, bold = true },
      DapUIDecoration = { fg = c.accent_dim },
      DapUIThread = { fg = c.ok },
      DapUIStoppedThread = { fg = c.accent_alt },
      DapUISource = { fg = c.func },
      DapUILineNumber = { fg = c.fg_dim },
      DapUIFloatBorder = { fg = c.border_alt, bg = c.bg_float },
      DapUIWatchesEmpty = { fg = c.fg_muted },
      DapUIWatchesValue = { fg = c.ok },
      DapUIWatchesError = { fg = c.err },
      DapUIBreakpointsPath = { fg = c.accent_alt },
      DapUIBreakpointsInfo = { fg = c.info },
      DapUIBreakpointsCurrentLine = { fg = c.annotation, bold = true },
    },

    navic = {
      NavicIconsFile = { fg = c.fg },
      NavicIconsModule = { fg = c.module },
      NavicIconsNamespace = { fg = c.module },
      NavicIconsClass = { fg = c.type },
      NavicIconsMethod = { fg = c.func },
      NavicIconsProperty = { fg = c.member },
      NavicIconsField = { fg = c.member },
      NavicIconsConstructor = { fg = c.type },
      NavicIconsEnum = { fg = c.type },
      NavicIconsInterface = { fg = c.type },
      NavicIconsFunction = { fg = c.func },
      NavicIconsVariable = { fg = c.variable },
      NavicIconsConstant = { fg = c.constant },
      NavicIconsString = { fg = c.string },
      NavicIconsNumber = { fg = c.number },
      NavicIconsBoolean = { fg = c.constant },
      NavicIconsKeyword = { fg = c.keyword },
      NavicText = { fg = c.fg },
      NavicSeparator = { fg = c.fg_dim },
    },

    dashboard = {
      DashboardHeader = { fg = c.accent },
      DashboardFooter = { fg = c.fg_dim, italic = true },
      DashboardIcon = { fg = c.func },
      DashboardDesc = { fg = c.fg },
      DashboardKey = { fg = c.annotation },
      DashboardShortCut = { fg = c.annotation },
      DashboardCenter = { fg = c.fg },
      DashboardProjectTitle = { fg = c.accent_alt, bold = true },
      DashboardProjectIcon = { fg = c.accent_alt },
      DashboardMruTitle = { fg = c.accent_alt, bold = true },
      DashboardMruIcon = { fg = c.accent_alt },
      DashboardFiles = { fg = c.fg },
      AlphaHeader = { fg = c.accent },
      AlphaButtons = { fg = c.fg },
      AlphaShortcut = { fg = c.annotation },
      AlphaFooter = { fg = c.fg_dim, italic = true },
    },

    yanky = {
      YankyPut = { bg = c.bg_match },
      YankyYanked = { bg = c.bg_match },
    },

    fidget = {
      FidgetTask = { fg = c.fg_dim },
      FidgetTitle = { fg = c.accent },
    },

    markdown = {
      RenderMarkdownH1Bg = { fg = c.keyword, bg = c.bg_line },
      RenderMarkdownH2Bg = { fg = c.func, bg = c.bg_line },
      RenderMarkdownH3Bg = { fg = c.type, bg = c.bg_line },
      RenderMarkdownH4Bg = { fg = c.number, bg = c.bg_line },
      RenderMarkdownH5Bg = { fg = c.annotation, bg = c.bg_line },
      RenderMarkdownH6Bg = { fg = c.fg_dim, bg = c.bg_line },
      RenderMarkdownCode = { bg = c.bg_alt },
      RenderMarkdownCodeInline = { fg = c.string, bg = c.bg_line },
      RenderMarkdownBullet = { fg = c.keyword },
      RenderMarkdownQuote = { fg = c.comment },
      RenderMarkdownLink = { fg = c.accent_alt },
      RenderMarkdownTableHead = { fg = c.func },
      RenderMarkdownTableRow = { fg = c.fg_dim },
    },
  }
end

return M
